"""
Alpha158 因子中文描述库 — 策略小课堂教学内容

每个因子包含: 名称、公式、中文释义、类别、教学解读
"""

FACTOR_CATEGORIES = {
    "price": "价格形态",
    "momentum": "动量因子",
    "trend": "趋势因子",
    "volatility": "波动因子",
    "volume": "量价因子",
    "quantile": "分位因子",
    "rank": "排名因子",
    "correlation": "相关性因子",
}

# 因子详细描述
FACTOR_DESCRIPTIONS = {
    # ── 价格形态 (KMID ~ VWAP0) ──
    "KMID":  {"category": "price", "formula": "($close-$open)/$open",
              "desc": "K线中间位置", "teaching": "反映当日收盘相对开盘的偏离程度。正值代表收阳线，负值代表收阴线。值越大，多头力量越强。"},
    "KLEN":  {"category": "price", "formula": "($high-$low)/$open",
              "desc": "K线长度", "teaching": "当日振幅（最高-最低）相对开盘价的比例。反映当日价格波动范围，值越大说明当日博弈越激烈。"},
    "KMID2": {"category": "price", "formula": "($close-$open)/($high-$low+1e-12)",
              "desc": "K线实体占比", "teaching": "实体部分（收盘-开盘）占全振幅的比例。接近1说明几乎全阳/全阴，接近0说明十字星。"},
    "KUP":   {"category": "price", "formula": "($high-max($open,$close))/$open",
              "desc": "上影线比例", "teaching": "上影线长度相对开盘价的比例。上影线长说明上方抛压重，多头未能守住高点。"},
    "KUP2":  {"category": "price", "formula": "($high-max($open,$close))/($high-$low+1e-12)",
              "desc": "上影线占振幅比", "teaching": "上影线占当日总振幅的比例。比例越高，上方阻力越明显。"},
    "KLOW":  {"category": "price", "formula": "(min($open,$close)-$low)/$open",
              "desc": "下影线比例", "teaching": "下影线长度相对开盘价的比例。下影线长说明下方支撑强，空头未能守住低点。"},
    "KLOW2": {"category": "price", "formula": "(min($open,$close)-$low)/($high-$low+1e-12)",
              "desc": "下影线占振幅比", "teaching": "下影线占当日总振幅的比例。比例越高，下方支撑越明显。"},
    "KSFT":  {"category": "price", "formula": "(2*$close-$high-$low)/$open",
              "desc": "收盘偏离中点", "teaching": "收盘价偏离当日中点（(最高+最低)/2）的程度。正值说明收在中点上方，偏强。"},
    "KSFT2": {"category": "price", "formula": "(2*$close-$high-$low)/($high-$low+1e-12)",
              "desc": "收盘偏离中点占比", "teaching": "收盘价偏离中点占振幅的比例。接近1说明收在最高点附近，接近-1说明收在最低点附近。"},
    "OPEN0": {"category": "price", "formula": "$open/$close",
              "desc": "开盘/收盘比", "teaching": "开盘价相对收盘价的比例。大于1说明低收，小于1说明高收。"},
    "HIGH0": {"category": "price", "formula": "$high/$close",
              "desc": "最高/收盘比", "teaching": "最高价相对收盘价的比例。值越接近1，说明收盘价接近最高点，多头强势。"},
    "LOW0":  {"category": "price", "formula": "$low/$close",
              "desc": "最低/收盘比", "teaching": "最低价相对收盘价的比例。值越接近1，说明收盘价接近最低点，空头强势。"},
    "VWAP0": {"category": "price", "formula": "$vwap/$close",
              "desc": "VWAP/收盘比", "teaching": "成交量加权平均价（VWAP）相对收盘价的比例。VWAP<收盘价说明尾盘拉升，VWAP>收盘价说明尾盘回落。"},

    # ── 动量因子 (ROC) ──
    "ROC5":  {"category": "momentum", "formula": "Ref($close,5)/$close",
              "desc": "5日收益率", "teaching": "5日前收盘价与当前收盘价的比值。小于1说明5日内上涨，大于1说明下跌。是短期动量的基础指标。"},
    "ROC10": {"category": "momentum", "formula": "Ref($close,10)/$close",
              "desc": "10日收益率", "teaching": "10日前收盘价与当前收盘价的比值。反映两周的动量变化。"},
    "ROC20": {"category": "momentum", "formula": "Ref($close,20)/$close",
              "desc": "20日收益率", "teaching": "20日前收盘价与当前收盘价的比值。约一个月的动量，常用于判断中期趋势。"},
    "ROC30": {"category": "momentum", "formula": "Ref($close,30)/$close",
              "desc": "30日收益率", "teaching": "30日动量。一个月以上的中期动量信号。"},
    "ROC60": {"category": "momentum", "formula": "Ref($close,60)/$close",
              "desc": "60日收益率", "teaching": "60日动量。季度级别的动量，适合捕捉中期趋势。"},

    # ── 趋势因子 (MA, BETA, RSQR, RESI) ──
    "MA5":   {"category": "trend", "formula": "Mean($close,5)/$close",
              "desc": "5日均线比", "teaching": "5日均线与收盘价的比值。大于1说明价格在均线下方（偏弱），小于1说明在均线上方（偏强）。"},
    "MA10":  {"category": "trend", "formula": "Mean($close,10)/$close", "desc": "10日均线比",
              "teaching": "10日均线与收盘价的比值，反映短期趋势方向。"},
    "MA20":  {"category": "trend", "formula": "Mean($close,20)/$close", "desc": "20日均线比",
              "teaching": "20日均线（月线）与收盘价的比值。是判断中期趋势的重要参考。"},
    "MA30":  {"category": "trend", "formula": "Mean($close,30)/$close", "desc": "30日均线比",
              "teaching": "30日均线与收盘价的比值。"},
    "MA60":  {"category": "trend", "formula": "Mean($close,60)/$close", "desc": "60日均线比",
              "teaching": "60日均线（季线）与收盘价的比值。季线是A股重要的趋势分界线。"},
    "BETA5": {"category": "trend", "formula": "Slope($close,5)/$close", "desc": "5日斜率",
              "teaching": "5日内收盘价线性回归斜率。正值代表上升趋势，负值代表下降趋势。"},
    "BETA10":{"category": "trend", "formula": "Slope($close,10)/$close", "desc": "10日斜率",
              "teaching": "10日线性趋势斜率，比5日更稳定。"},
    "BETA20":{"category": "trend", "formula": "Slope($close,20)/$close", "desc": "20日斜率",
              "teaching": "20日线性趋势斜率，反映中期趋势方向。"},
    "BETA30":{"category": "trend", "formula": "Slope($close,30)/$close", "desc": "30日斜率",
              "teaching": "30日线性趋势斜率。"},
    "BETA60":{"category": "trend", "formula": "Slope($close,60)/$close", "desc": "60日斜率",
              "teaching": "60日线性趋势斜率，季度级别趋势判断。"},
    "RSQR5": {"category": "trend", "formula": "Rsquare($close,5)", "desc": "5日R²",
              "teaching": "5日线性回归的R²（拟合优度）。越接近1说明趋势越线性（稳定上涨或下跌），接近0说明无明确趋势。"},
    "RSQR10":{"category": "trend", "formula": "Rsquare($close,10)", "desc": "10日R²",
              "teaching": "10日线性回归拟合优度。"},
    "RSQR20":{"category": "trend", "formula": "Rsquare($close,20)", "desc": "20日R²",
              "teaching": "20日线性回归拟合优度。"},
    "RSQR30":{"category": "trend", "formula": "Rsquare($close,30)", "desc": "30日R²",
              "teaching": "30日线性回归拟合优度。"},
    "RSQR60":{"category": "trend", "formula": "Rsquare($close,60)", "desc": "60日R²",
              "teaching": "60日线性回归拟合优度。"},
    "RESI5": {"category": "trend", "formula": "Resi($close,5)/$close", "desc": "5日残差",
              "teaching": "5日线性回归的残差（实际值偏离趋势线的程度）。值大说明价格波动偏离趋势线远。"},
    "RESI10":{"category": "trend", "formula": "Resi($close,10)/$close", "desc": "10日残差",
              "teaching": "10日线性回归残差。"},
    "RESI20":{"category": "trend", "formula": "Resi($close,20)/$close", "desc": "20日残差",
              "teaching": "20日线性回归残差。"},
    "RESI30":{"category": "trend", "formula": "Resi($close,30)/$close", "desc": "30日残差",
              "teaching": "30日线性回归残差。"},
    "RESI60":{"category": "trend", "formula": "Resi($close,60)/$close", "desc": "60日残差",
              "teaching": "60日线性回归残差。"},

    # ── 波动因子 (STD, MAX, MIN) ──
    "STD5":  {"category": "volatility", "formula": "Std($close,5)/$close", "desc": "5日标准差",
              "teaching": "5日收盘价标准差相对收盘价的比例。反映短期波动率，值越大风险越高。"},
    "STD10": {"category": "volatility", "formula": "Std($close,10)/$close", "desc": "10日标准差",
              "teaching": "10日波动率。"},
    "STD20": {"category": "volatility", "formula": "Std($close,20)/$close", "desc": "20日标准差",
              "teaching": "20日波动率，约一个月的历史波动率。"},
    "STD30": {"category": "volatility", "formula": "Std($close,30)/$close", "desc": "30日标准差",
              "teaching": "30日波动率。"},
    "STD60": {"category": "volatility", "formula": "Std($close,60)/$close", "desc": "60日标准差",
              "teaching": "60日波动率，季度级别的历史波动率。"},
    "MAX5":  {"category": "volatility", "formula": "Max($high,5)/$close", "desc": "5日最高价",
              "teaching": "近5日最高价与当前收盘价的比值。大于1说明当前价格低于近期高点。"},
    "MAX10": {"category": "volatility", "formula": "Max($high,10)/$close", "desc": "10日最高价",
              "teaching": "近10日最高价与收盘价之比。"},
    "MAX20": {"category": "volatility", "formula": "Max($high,20)/$close", "desc": "20日最高价",
              "teaching": "近20日最高价与收盘价之比。"},
    "MAX30": {"category": "volatility", "formula": "Max($high,30)/$close", "desc": "30日最高价",
              "teaching": "近30日最高价与收盘价之比。"},
    "MAX60": {"category": "volatility", "formula": "Max($high,60)/$close", "desc": "60日最高价",
              "teaching": "近60日最高价与收盘价之比。比值越小说明当前价格越接近季度高点。"},
    "MIN5":  {"category": "volatility", "formula": "Min($low,5)/$close", "desc": "5日最低价",
              "teaching": "近5日最低价与收盘价的比值。"},
    "MIN10": {"category": "volatility", "formula": "Min($low,10)/$close", "desc": "10日最低价",
              "teaching": "近10日最低价与收盘价之比。"},
    "MIN20": {"category": "volatility", "formula": "Min($low,20)/$close", "desc": "20日最低价",
              "teaching": "近20日最低价与收盘价之比。"},
    "MIN30": {"category": "volatility", "formula": "Min($low,30)/$close", "desc": "30日最低价",
              "teaching": "近30日最低价与收盘价之比。"},
    "MIN60": {"category": "volatility", "formula": "Min($low,60)/$close", "desc": "60日最低价",
              "teaching": "近60日最低价与收盘价之比。比值越接近1说明当前价格接近季度低点。"},

    # ── 分位因子 (QTLU, QTLD, RSV) ──
    "QTLU5": {"category": "quantile", "formula": "Quantile($close,5,0.8)/$close", "desc": "5日80%分位",
              "teaching": "近5日收盘价80%分位数与当前收盘价之比。比值大于1说明当前价格低于近5日80%分位（偏弱）。"},
    "QTLU10":{"category": "quantile", "formula": "Quantile($close,10,0.8)/$close", "desc": "10日80%分位",
              "teaching": "近10日收盘价80%分位数与收盘价之比。"},
    "QTLU20":{"category": "quantile", "formula": "Quantile($close,20,0.8)/$close", "desc": "20日80%分位",
              "teaching": "近20日收盘价80%分位数与收盘价之比。"},
    "QTLU30":{"category": "quantile", "formula": "Quantile($close,30,0.8)/$close", "desc": "30日80%分位",
              "teaching": "近30日收盘价80%分位数与收盘价之比。"},
    "QTLU60":{"category": "quantile", "formula": "Quantile($close,60,0.8)/$close", "desc": "60日80%分位",
              "teaching": "近60日收盘价80%分位数与收盘价之比。"},
    "QTLD5": {"category": "quantile", "formula": "Quantile($close,5,0.2)/$close", "desc": "5日20%分位",
              "teaching": "近5日收盘价20%分位数与收盘价之比。比值大于1说明当前价格高于近5日20%分位。"},
    "QTLD10":{"category": "quantile", "formula": "Quantile($close,10,0.2)/$close", "desc": "10日20%分位",
              "teaching": "近10日收盘价20%分位数与收盘价之比。"},
    "QTLD20":{"category": "quantile", "formula": "Quantile($close,20,0.2)/$close", "desc": "20日20%分位",
              "teaching": "近20日收盘价20%分位数与收盘价之比。"},
    "QTLD30":{"category": "quantile", "formula": "Quantile($close,30,0.2)/$close", "desc": "30日20%分位",
              "teaching": "近30日收盘价20%分位数与收盘价之比。"},
    "QTLD60":{"category": "quantile", "formula": "Quantile($close,60,0.2)/$close", "desc": "60日20%分位",
              "teaching": "近60日收盘价20%分位数与收盘价之比。"},
    "RSV5":  {"category": "quantile", "formula": "($close-Min($low,5))/(Max($high,5)-Min($low,5)+1e-12)",
              "desc": "5日RSV", "teaching": "随机指标RSV。衡量收盘价在近5日高低区间的位置。0=最低点，1=最高点。KD指标的原始值。"},
    "RSV10": {"category": "quantile", "formula": "($close-Min($low,10))/(Max($high,10)-Min($low,10)+1e-12)",
              "desc": "10日RSV", "teaching": "10日随机指标。"},
    "RSV20": {"category": "quantile", "formula": "($close-Min($low,20))/(Max($high,20)-Min($low,20)+1e-12)",
              "desc": "20日RSV", "teaching": "20日随机指标。"},
    "RSV30": {"category": "quantile", "formula": "($close-Min($low,30))/(Max($high,30)-Min($low,30)+1e-12)",
              "desc": "30日RSV", "teaching": "30日随机指标。"},
    "RSV60": {"category": "quantile", "formula": "($close-Min($low,60))/(Max($high,60)-Min($low,60)+1e-12)",
              "desc": "60日RSV", "teaching": "60日随机指标。反映收盘价在季度高低区间的位置。"},

    # ── 排名因子 (RANK, IMAX, IMIN, IMXD) ──
    "RANK5": {"category": "rank", "formula": "Rank($close,5)", "desc": "5日排名",
              "teaching": "当前收盘价在近5日收盘价中的排名比例。1=最高，0=最低。"},
    "RANK10":{"category": "rank", "formula": "Rank($close,10)", "desc": "10日排名",
              "teaching": "当前收盘价在近10日中的排名比例。"},
    "RANK20":{"category": "rank", "formula": "Rank($close,20)", "desc": "20日排名",
              "teaching": "当前收盘价在近20日中的排名比例。"},
    "RANK30":{"category": "rank", "formula": "Rank($close,30)", "desc": "30日排名",
              "teaching": "当前收盘价在近30日中的排名比例。"},
    "RANK60":{"category": "rank", "formula": "Rank($close,60)", "desc": "60日排名",
              "teaching": "当前收盘价在近60日中的排名比例。"},
    "IMAX5":{"category": "rank", "formula": "IdxMax($high,5)/5", "desc": "5日最高价位置",
             "teaching": "近5日最高价出现的位置（归一化到0-1）。0.5说明最高价在中间，接近1说明最高价在最近。"},
    "IMAX10":{"category": "rank", "formula": "IdxMax($high,10)/10", "desc": "10日最高价位置", "teaching": "近10日最高价出现位置。"},
    "IMAX20":{"category": "rank", "formula": "IdxMax($high,20)/20", "desc": "20日最高价位置", "teaching": "近20日最高价出现位置。"},
    "IMAX30":{"category": "rank", "formula": "IdxMax($high,30)/30", "desc": "30日最高价位置", "teaching": "近30日最高价出现位置。"},
    "IMAX60":{"category": "rank", "formula": "IdxMax($high,60)/60", "desc": "60日最高价位置", "teaching": "近60日最高价出现位置。接近1=高点在最近，接近0=高点在早期。"},
    "IMIN5":{"category": "rank", "formula": "IdxMin($low,5)/5", "desc": "5日最低价位置", "teaching": "近5日最低价出现位置。"},
    "IMIN10":{"category": "rank", "formula": "IdxMin($low,10)/10", "desc": "10日最低价位置", "teaching": "近10日最低价出现位置。"},
    "IMIN20":{"category": "rank", "formula": "IdxMin($low,20)/20", "desc": "20日最低价位置", "teaching": "近20日最低价出现位置。"},
    "IMIN30":{"category": "rank", "formula": "IdxMin($low,30)/30", "desc": "30日最低价位置", "teaching": "近30日最低价出现位置。"},
    "IMIN60":{"category": "rank", "formula": "IdxMin($low,60)/60", "desc": "60日最低价位置", "teaching": "近60日最低价出现位置。接近1=低点在最近。"},
    "IMXD5":{"category": "rank", "formula": "(IdxMax($high,5)-IdxMin($low,5))/5", "desc": "5日高低点距离", "teaching": "最高价位置与最低价位置的距离。值大说明高低点相隔远（震荡行情），值小说明高低点接近（单边行情）。"},
    "IMXD10":{"category": "rank", "formula": "(IdxMax($high,10)-IdxMin($low,10))/10", "desc": "10日高低点距离", "teaching": "10日高低点位置距离。"},
    "IMXD20":{"category": "rank", "formula": "(IdxMax($high,20)-IdxMin($low,20))/20", "desc": "20日高低点距离", "teaching": "20日高低点位置距离。"},
    "IMXD30":{"category": "rank", "formula": "(IdxMax($high,30)-IdxMin($low,30))/30", "desc": "30日高低点距离", "teaching": "30日高低点位置距离。"},
    "IMXD60":{"category": "rank", "formula": "(IdxMax($high,60)-IdxMin($low,60))/60", "desc": "60日高低点距离", "teaching": "60日高低点位置距离。"},

    # ── 相关性因子 (CORR, CORD) ──
    "CORR5":{"category": "correlation", "formula": "Corr($close,Log($volume+1),5)", "desc": "5日量价相关",
             "teaching": "5日内收盘价与成交量对数的相关系数。正相关说明放量上涨（量价配合），负相关说明放量下跌。"},
    "CORR10":{"category": "correlation", "formula": "Corr($close,Log($volume+1),10)", "desc": "10日量价相关", "teaching": "10日量价相关系数。"},
    "CORR20":{"category": "correlation", "formula": "Corr($close,Log($volume+1),20)", "desc": "20日量价相关", "teaching": "20日量价相关系数。"},
    "CORR30":{"category": "correlation", "formula": "Corr($close,Log($volume+1),30)", "desc": "30日量价相关", "teaching": "30日量价相关系数。"},
    "CORR60":{"category": "correlation", "formula": "Corr($close,Log($volume+1),60)", "desc": "60日量价相关", "teaching": "60日量价相关系数。正值且较大说明持续放量上涨，是健康趋势的标志。"},
    "CORD5":{"category": "correlation", "formula": "Corr($close/Ref($close,1),Log($volume/Ref($volume,1)+1),5)", "desc": "5日变化量价相关",
             "teaching": "5日内日收益率与成交量变化的相关系数。衡量量价变化的同步性。"},
    "CORD10":{"category": "correlation", "formula": "Corr($close/Ref($close,1),Log($volume/Ref($volume,1)+1),10)", "desc": "10日变化量价相关", "teaching": "10日量价变化相关系数。"},
    "CORD20":{"category": "correlation", "formula": "Corr($close/Ref($close,1),Log($volume/Ref($volume,1)+1),20)", "desc": "20日变化量价相关", "teaching": "20日量价变化相关系数。"},
    "CORD30":{"category": "correlation", "formula": "Corr($close/Ref($close,1),Log($volume/Ref($volume,1)+1),30)", "desc": "30日变化量价相关", "teaching": "30日量价变化相关系数。"},
    "CORD60":{"category": "correlation", "formula": "Corr($close/Ref($close,1),Log($volume/Ref($volume,1)+1),60)", "desc": "60日变化量价相关", "teaching": "60日量价变化相关系数。"},

    # ── 涨跌统计因子 (CNTP, CNTN, CNTD) ──
    "CNTP5":{"category": "momentum", "formula": "Mean($close>Ref($close,1),5)", "desc": "5日上涨比例",
             "teaching": "近5日中上涨日占比。0.6=5天中3天上涨。值越高短期越强势。"},
    "CNTP10":{"category": "momentum", "formula": "Mean($close>Ref($close,1),10)", "desc": "10日上涨比例", "teaching": "近10日上涨日占比。"},
    "CNTP20":{"category": "momentum", "formula": "Mean($close>Ref($close,1),20)", "desc": "20日上涨比例", "teaching": "近20日上涨日占比。约一个月的涨跌天数比。"},
    "CNTP30":{"category": "momentum", "formula": "Mean($close>Ref($close,1),30)", "desc": "30日上涨比例", "teaching": "近30日上涨日占比。"},
    "CNTP60":{"category": "momentum", "formula": "Mean($close>Ref($close,1),60)", "desc": "60日上涨比例", "teaching": "近60日上涨日占比。0.5=涨跌各半。"},
    "CNTN5":{"category": "momentum", "formula": "Mean($close<Ref($close,1),5)", "desc": "5日下跌比例", "teaching": "近5日中下跌日占比。"},
    "CNTN10":{"category": "momentum", "formula": "Mean($close<Ref($close,1),10)", "desc": "10日下跌比例", "teaching": "近10日下跌日占比。"},
    "CNTN20":{"category": "momentum", "formula": "Mean($close<Ref($close,1),20)", "desc": "20日下跌比例", "teaching": "近20日下跌日占比。"},
    "CNTN30":{"category": "momentum", "formula": "Mean($close<Ref($close,1),30)", "desc": "30日下跌比例", "teaching": "近30日下跌日占比。"},
    "CNTN60":{"category": "momentum", "formula": "Mean($close<Ref($close,1),60)", "desc": "60日下跌比例", "teaching": "近60日下跌日占比。"},
    "CNTD5":{"category": "momentum", "formula": "Mean($close>Ref($close,1),5)-Mean($close<Ref($close,1),5)", "desc": "5日涨跌天差", "teaching": "近5日上涨占比减下跌占比。正值偏多，负值偏空。范围-1到1。"},
    "CNTD10":{"category": "momentum", "formula": "Mean($close>Ref($close,1),10)-Mean($close<Ref($close,1),10)", "desc": "10日涨跌天差", "teaching": "10日涨跌天数差。"},
    "CNTD20":{"category": "momentum", "formula": "Mean($close>Ref($close,1),20)-Mean($close<Ref($close,1),20)", "desc": "20日涨跌天差", "teaching": "20日涨跌天数差。"},
    "CNTD30":{"category": "momentum", "formula": "Mean($close>Ref($close,1),30)-Mean($close<Ref($close,1),30)", "desc": "30日涨跌天差", "teaching": "30日涨跌天数差。"},
    "CNTD60":{"category": "momentum", "formula": "Mean($close>Ref($close,1),60)-Mean($close<Ref($close,1),60)", "desc": "60日涨跌天差", "teaching": "60日涨跌天数差。"},

    # ── 涨跌幅度因子 (SUMP, SUMN, SUMD) ──
    "SUMP5":{"category": "momentum", "formula": "Sum(Greater($close-Ref($close,1),0),5)/(Sum(Abs($close-Ref($close,1)),5)+1e-12)",
             "desc": "5日涨幅占比", "teaching": "近5日上涨幅度总和占总波动幅度的比例。0.6=上涨贡献了60%的波动。类似RSI指标。"},
    "SUMP10":{"category": "momentum", "formula": "Sum(Greater($close-Ref($close,1),0),10)/(Sum(Abs($close-Ref($close,1)),10)+1e-12)", "desc": "10日涨幅占比", "teaching": "10日上涨幅度占比。"},
    "SUMP20":{"category": "momentum", "formula": "Sum(Greater($close-Ref($close,1),0),20)/(Sum(Abs($close-Ref($close,1)),20)+1e-12)", "desc": "20日涨幅占比", "teaching": "20日上涨幅度占比，类似20日RSI。"},
    "SUMP30":{"category": "momentum", "formula": "Sum(Greater($close-Ref($close,1),0),30)/(Sum(Abs($close-Ref($close,1)),30)+1e-12)", "desc": "30日涨幅占比", "teaching": "30日上涨幅度占比。"},
    "SUMP60":{"category": "momentum", "formula": "Sum(Greater($close-Ref($close,1),0),60)/(Sum(Abs($close-Ref($close,1)),60)+1e-12)", "desc": "60日涨幅占比", "teaching": "60日上涨幅度占比。"},
    "SUMN5":{"category": "momentum", "formula": "Sum(Greater(Ref($close,1)-$close,0),5)/(Sum(Abs($close-Ref($close,1)),5)+1e-12)", "desc": "5日跌幅占比", "teaching": "近5日下跌幅度占总波动的比例。"},
    "SUMN10":{"category": "momentum", "formula": "Sum(Greater(Ref($close,1)-$close,0),10)/(Sum(Abs($close-Ref($close,1)),10)+1e-12)", "desc": "10日跌幅占比", "teaching": "10日下跌幅度占比。"},
    "SUMN20":{"category": "momentum", "formula": "Sum(Greater(Ref($close,1)-$close,0),20)/(Sum(Abs($close-Ref($close,1)),20)+1e-12)", "desc": "20日跌幅占比", "teaching": "20日下跌幅度占比。"},
    "SUMN30":{"category": "momentum", "formula": "Sum(Greater(Ref($close,1)-$close,0),30)/(Sum(Abs($close-Ref($close,1)),30)+1e-12)", "desc": "30日跌幅占比", "teaching": "30日下跌幅度占比。"},
    "SUMN60":{"category": "momentum", "formula": "Sum(Greater(Ref($close,1)-$close,0),60)/(Sum(Abs($close-Ref($close,1)),60)+1e-12)", "desc": "60日跌幅占比", "teaching": "60日下跌幅度占比。"},
    "SUMD5":{"category": "momentum", "formula": "(Sum(Greater($close-Ref($close,1),0),5)-Sum(Greater(Ref($close,1)-$close,0),5))/(Sum(Abs($close-Ref($close,1)),5)+1e-12)",
             "desc": "5日涨跌幅差", "teaching": "涨幅占比减跌幅占比。类似RSI的变形，范围-1到1。"},
    "SUMD10":{"category": "momentum", "formula": "(Sum(Greater($close-Ref($close,1),0),10)-Sum(Greater(Ref($close,1)-$close,0),10))/(Sum(Abs($close-Ref($close,1)),10)+1e-12)", "desc": "10日涨跌幅差", "teaching": "10日涨跌幅差。"},
    "SUMD20":{"category": "momentum", "formula": "(Sum(Greater($close-Ref($close,1),0),20)-Sum(Greater(Ref($close,1)-$close,0),20))/(Sum(Abs($close-Ref($close,1)),20)+1e-12)", "desc": "20日涨跌幅差", "teaching": "20日涨跌幅差。"},
    "SUMD30":{"category": "momentum", "formula": "(Sum(Greater($close-Ref($close,1),0),30)-Sum(Greater(Ref($close,1)-$close,0),30))/(Sum(Abs($close-Ref($close,1)),30)+1e-12)", "desc": "30日涨跌幅差", "teaching": "30日涨跌幅差。"},
    "SUMD60":{"category": "momentum", "formula": "(Sum(Greater($close-Ref($close,1),0),60)-Sum(Greater(Ref($close,1)-$close,0),60))/(Sum(Abs($close-Ref($close,1)),60)+1e-12)", "desc": "60日涨跌幅差", "teaching": "60日涨跌幅差。"},

    # ── 成交量因子 (VMA, VSTD, WVMA) ──
    "VMA5":{"category": "volume", "formula": "Mean($volume,5)/($volume+1e-12)", "desc": "5日均量比",
            "teaching": "5日均量与当前成交量之比。大于1说明今日缩量，小于1说明今日放量。"},
    "VMA10":{"category": "volume", "formula": "Mean($volume,10)/($volume+1e-12)", "desc": "10日均量比", "teaching": "10日均量与当前成交量之比。"},
    "VMA20":{"category": "volume", "formula": "Mean($volume,20)/($volume+1e-12)", "desc": "20日均量比", "teaching": "20日均量与当前成交量之比。"},
    "VMA30":{"category": "volume", "formula": "Mean($volume,30)/($volume+1e-12)", "desc": "30日均量比", "teaching": "30日均量与当前成交量之比。"},
    "VMA60":{"category": "volume", "formula": "Mean($volume,60)/($volume+1e-12)", "desc": "60日均量比", "teaching": "60日均量与当前成交量之比。"},
    "VSTD5":{"category": "volume", "formula": "Std($volume,5)/($volume+1e-12)", "desc": "5日量能波动", "teaching": "5日成交量标准差与当前成交量之比。反映成交量的波动程度。"},
    "VSTD10":{"category": "volume", "formula": "Std($volume,10)/($volume+1e-12)", "desc": "10日量能波动", "teaching": "10日成交量波动率。"},
    "VSTD20":{"category": "volume", "formula": "Std($volume,20)/($volume+1e-12)", "desc": "20日量能波动", "teaching": "20日成交量波动率。"},
    "VSTD30":{"category": "volume", "formula": "Std($volume,30)/($volume+1e-12)", "desc": "30日量能波动", "teaching": "30日成交量波动率。"},
    "VSTD60":{"category": "volume", "formula": "Std($volume,60)/($volume+1e-12)", "desc": "60日量能波动", "teaching": "60日成交量波动率。"},
    "WVMA5":{"category": "volume", "formula": "Std(Abs($close/Ref($close,1)-1)*$volume,5)/(Mean(Abs($close/Ref($close,1)-1)*$volume,5)+1e-12)",
             "desc": "5日加权量能波动", "teaching": "以价格变动幅度加权的成交量波动率。结合了价格变化和成交量变化，比纯量能波动更有信息量。"},
    "WVMA10":{"category": "volume", "formula": "Std(Abs($close/Ref($close,1)-1)*$volume,10)/(Mean(Abs($close/Ref($close,1)-1)*$volume,10)+1e-12)", "desc": "10日加权量能波动", "teaching": "10日加权成交量波动率。"},
    "WVMA20":{"category": "volume", "formula": "Std(Abs($close/Ref($close,1)-1)*$volume,20)/(Mean(Abs($close/Ref($close,1)-1)*$volume,20)+1e-12)", "desc": "20日加权量能波动", "teaching": "20日加权成交量波动率。"},
    "WVMA30":{"category": "volume", "formula": "Std(Abs($close/Ref($close,1)-1)*$volume,30)/(Mean(Abs($close/Ref($close,1)-1)*$volume,30)+1e-12)", "desc": "30日加权量能波动", "teaching": "30日加权成交量波动率。"},
    "WVMA60":{"category": "volume", "formula": "Std(Abs($close/Ref($close,1)-1)*$volume,60)/(Mean(Abs($close/Ref($close,1)-1)*$volume,60)+1e-12)", "desc": "60日加权量能波动", "teaching": "60日加权成交量波动率。"},

    # ── 成交量涨跌因子 (VSUMP, VSUMN, VSUMD) ──
    "VSUMP5":{"category": "volume", "formula": "Sum(Greater($volume-Ref($volume,1),0),5)/(Sum(Abs($volume-Ref($volume,1)),5)+1e-12)",
              "desc": "5日放量占比", "teaching": "近5日放量幅度占总成交量变化的比值。类似成交量的RSI。"},
    "VSUMP10":{"category": "volume", "formula": "Sum(Greater($volume-Ref($volume,1),0),10)/(Sum(Abs($volume-Ref($volume,1)),10)+1e-12)", "desc": "10日放量占比", "teaching": "10日放量幅度占比。"},
    "VSUMP20":{"category": "volume", "formula": "Sum(Greater($volume-Ref($volume,1),0),20)/(Sum(Abs($volume-Ref($volume,1)),20)+1e-12)", "desc": "20日放量占比", "teaching": "20日放量幅度占比。"},
    "VSUMP30":{"category": "volume", "formula": "Sum(Greater($volume-Ref($volume,1),0),30)/(Sum(Abs($volume-Ref($volume,1)),30)+1e-12)", "desc": "30日放量占比", "teaching": "30日放量幅度占比。"},
    "VSUMP60":{"category": "volume", "formula": "Sum(Greater($volume-Ref($volume,1),0),60)/(Sum(Abs($volume-Ref($volume,1)),60)+1e-12)", "desc": "60日放量占比", "teaching": "60日放量幅度占比。"},
    "VSUMN5":{"category": "volume", "formula": "Sum(Greater(Ref($volume,1)-$volume,0),5)/(Sum(Abs($volume-Ref($volume,1)),5)+1e-12)", "desc": "5日缩量占比", "teaching": "近5日缩量幅度占比。"},
    "VSUMN10":{"category": "volume", "formula": "Sum(Greater(Ref($volume,1)-$volume,0),10)/(Sum(Abs($volume-Ref($volume,1)),10)+1e-12)", "desc": "10日缩量占比", "teaching": "10日缩量幅度占比。"},
    "VSUMN20":{"category": "volume", "formula": "Sum(Greater(Ref($volume,1)-$volume,0),20)/(Sum(Abs($volume-Ref($volume,1)),20)+1e-12)", "desc": "20日缩量占比", "teaching": "20日缩量幅度占比。"},
    "VSUMN30":{"category": "volume", "formula": "Sum(Greater(Ref($volume,1)-$volume,0),30)/(Sum(Abs($volume-Ref($volume,1)),30)+1e-12)", "desc": "30日缩量占比", "teaching": "30日缩量幅度占比。"},
    "VSUMN60":{"category": "volume", "formula": "Sum(Greater(Ref($volume,1)-$volume,0),60)/(Sum(Abs($volume-Ref($volume,1)),60)+1e-12)", "desc": "60日缩量占比", "teaching": "60日缩量幅度占比。"},
    "VSUMD5":{"category": "volume", "formula": "(Sum(Greater($volume-Ref($volume,1),0),5)-Sum(Greater(Ref($volume,1)-$volume,0),5))/(Sum(Abs($volume-Ref($volume,1)),5)+1e-12)",
              "desc": "5日量能差", "teaching": "放量占比减缩量占比，范围-1到1。正值偏放量，负值偏缩量。"},
    "VSUMD10":{"category": "volume", "formula": "(Sum(Greater($volume-Ref($volume,1),0),10)-Sum(Greater(Ref($volume,1)-$volume,0),10))/(Sum(Abs($volume-Ref($volume,1)),10)+1e-12)", "desc": "10日量能差", "teaching": "10日量能差。"},
    "VSUMD20":{"category": "volume", "formula": "(Sum(Greater($volume-Ref($volume,1),0),20)-Sum(Greater(Ref($volume,1)-$volume,0),20))/(Sum(Abs($volume-Ref($volume,1)),20)+1e-12)", "desc": "20日量能差", "teaching": "20日量能差。"},
    "VSUMD30":{"category": "volume", "formula": "(Sum(Greater($volume-Ref($volume,1),0),30)-Sum(Greater(Ref($volume,1)-$volume,0),30))/(Sum(Abs($volume-Ref($volume,1)),30)+1e-12)", "desc": "30日量能差", "teaching": "30日量能差。"},
    "VSUMD60":{"category": "volume", "formula": "(Sum(Greater($volume-Ref($volume,1),0),60)-Sum(Greater(Ref($volume,1)-$volume,0),60))/(Sum(Abs($volume-Ref($volume,1)),60)+1e-12)", "desc": "60日量能差", "teaching": "60日量能差。正值=持续放量趋势，负值=持续缩量。"},
}


def get_factor_info(name: str) -> dict:
    """获取单个因子的完整信息"""
    return FACTOR_DESCRIPTIONS.get(name, {
        "category": "other",
        "formula": "",
        "desc": name,
        "teaching": "该因子的教学描述待补充。",
    })


def get_all_factor_names() -> list[str]:
    """获取所有因子名称（按顺序）"""
    return list(FACTOR_DESCRIPTIONS.keys())


def get_factors_by_category(category: str) -> list[str]:
    """按类别获取因子"""
    return [name for name, info in FACTOR_DESCRIPTIONS.items()
            if info["category"] == category]


def get_category_summary() -> dict:
    """获取类别统计"""
    summary = {}
    for name, info in FACTOR_DESCRIPTIONS.items():
        cat = info["category"]
        if cat not in summary:
            summary[cat] = {"count": 0, "label": FACTOR_CATEGORIES.get(cat, cat)}
        summary[cat]["count"] += 1
    return summary
